### ISSUE TITLE
Create and Update Milestone V1

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/scip-python#15]
- [x] Create new milestone
- [x] Investigate rest of Python feature set we'd be interested in, and create issues here
- [x] Assign appropriate issues to v1
- [ ] Create website pitching v1 features

**Comment by tjdevries** [comment]
Not creating a website, will put on sourcegraph docs soon (in same style as lsif-typescript)
